# Generated by Django 5.2.12 on 2026-05-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing_banners/')),
                ('content', models.TextField(blank=True, null=True, verbose_name='text/content')),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketing_banner',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
