# Generated by Motohub – adds extra product fields for dynamic form support

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_alert',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='compatibility_type',
            field=models.CharField(
                blank=True,
                help_text='Car / Bike / Truck / Universal',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='compatibility_tags',
            field=models.CharField(
                blank=True,
                help_text='Comma-separated vehicle models, e.g. BMW 3 Series, Honda City',
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(
                blank=True,
                default='No Warranty',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(
                blank=True,
                default='Non-returnable',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.CharField(default='published', max_length=20),
        ),
    ]
