# Generated by Django 5.2.12 on 2026-04-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('button_text', models.CharField(default='SHOP NOW', max_length=50)),
                ('button_link', models.CharField(default='coming-soon.html', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific dynamic specifications as key-value pairs.'),
        ),
    ]
