# Generated by Django 5.2.12 on 2026-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_banner_alter_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
