# Generated by Django 5.2.12 on 2026-04-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_banner_image_file_alter_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('service', 'Service Banner'), ('promo_1', 'Promo Banner 1'), ('promo_2', 'Promo Banner 2')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('button_text', models.CharField(default='SHOP NOW', max_length=50)),
                ('button_link', models.CharField(default='coming-soon.html', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['banner_type'],
            },
        ),
    ]
