# Generated by Django 5.2.12 on 2026-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 5', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='banner_type',
            field=models.CharField(choices=[('service', 'Service Banner'), ('promo_1', 'Promo Banner 1'), ('promo_2', 'Promo Banner 2'), ('widget_product', 'Sidebar Product Widget'), ('widget_vertical', 'Sidebar Vertical Banner')], max_length=20, unique=True),
        ),
    ]
