# Generated by Django 6.0.3 on 2026-04-03 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_permissions_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='permissions_config',
            field=models.JSONField(blank=True, default=dict, help_text='Custom permission map for moderators.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('garage', 'Garage'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='GarageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('gstin', models.CharField(blank=True, max_length=20, null=True, verbose_name='GSTIN')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garage_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
